### ISSUE TITLE
Wiki page crashes

### ISSUE THREAD

**Issue by sthashakun** [credativUK/redmine_image_clipboard_paste#10]
After install the plugin, wiki page is not working.

Here is the exception thrown.

ActionView::Template::Error (':parent' is not an ActiveModel-compatible object that returns a valid partial path.):
    1: <%= javascript_include_tag 'image_paste.js', :plugin => 'redmine_image_clipboard_paste' %>
    2: <%= render :parent, {:you_can_pass => :locals} %>
  app/controllers/wiki_controller.rb:73:in `show' 

I'm using the following version.

Redmine version                2.5.2.stable
  Ruby version                   1.9.3-p231 (2012-05-25) [i386-mingw32]
  Rails version                  3.2.19

**Comment by tornoz** [comment]
Hello,

The latest version of the plugin, which enables the functionalities on wiki and forum pages, needs the gem "render_parent" to be installed.
Either installing the missing gem or downgrading the plugin of one commit should resolve your issue.

**Comment by fsalas** [comment]
Can you post a fix please , I faced the same poblem tried gem install 'render_parent' , but error persist, or what would be the instruction to fix it, forums crash also all with similar problem

ActionView::Template::Error (':parent' is not an ActiveModel-compatible object that returns a valid partial path.):
    1: <%= javascript_include_tag 'image_paste.js', :plugin => 'redmine_image_clipboard_paste' %>
    2: <%= render :parent, {:you_can_pass => :locals} %>
  app/controllers/boards_controller.rb:55:in `block (2 levels) in show'
  app/controllers/boards_controller.rb:37:in`show'
  app/controllers/boards_controller.rb:32:in `index'

trying to unistall renders the system unusable with an general error page

Thanks in advance

**Comment by pinghe** [comment]
me too

**Comment by TeamForrest** [comment]
I am having the same problem as well.

**Comment by yincp** [comment]
me too. crash still exists after render_parent is installed

**Comment by arnisjuraga** [comment]
#14 - the same issue?

**Comment by razimi** [comment]
Any update on how to fix this issues? 

![image](https://cloud.githubusercontent.com/assets/1865490/7362952/960ca0d0-eda4-11e4-8109-abf011d149c2.png)

![image](https://cloud.githubusercontent.com/assets/1865490/7362967/c67c5c74-eda4-11e4-9852-44471f13d17a.png)

**Comment by ninjasenses** [comment]
Not sure if anyone is still looking for this but I experienced the same issue while upgrading from redmine 2.5 -> 3.0.3.  **The only way I was able to resolve the issue was to completly remove the <redmineInstallLoc>/plugins/redmine_image_clipboard_paste/app/views/wiki directory and its subfiles.**  I was then able to edit the wiki again.  I am using redmine_image_clipboard_paste v. 1.0.0

**Comment by arnisjuraga** [comment]
Workaround, by the way, is to:
1. If You have installed plugin already - remove it! If You have not installed yet - do not install. 
2. copy all .js code from plugin file `assets/javascript/image_paste.js`
3. paste it at the end of Your's theme javascript file, e.g. `public/themes/THEMENAME/javascripts/theme.js`

It is now working like this just fine for me.
