### ISSUE TITLE
redmine 2.6 fail on wiki

### ISSUE THREAD

**Issue by pinghe** [credativUK/redmine_image_clipboard_paste#14]
```
Completed 500 Internal Server Error in 17.6ms

ActionView::Template::Error (':parent' is not an ActiveModel-compatible object that returns a valid partial path.):
    1: <%= javascript_include_tag 'image_paste.js', :plugin => 'redmine_image_clipboard_paste' %>
    2: <%= render :parent, {:you_can_pass => :locals} %>
    3: 
  app/controllers/wiki_controller.rb:73:in `show'
```

my plugins:

```
redmine_agile
redmine_checklists
redmine_favorite_projects
redmine_image_clipboard_paste
redmine_knowledgebase
redmine_people
redmine_questions
redmine_zenedit
```

gems:

```
Using rake 10.3.2
Using i18n 0.6.11
Using multi_json 1.10.1
Using activesupport 3.2.19
Using builder 3.0.4
Using activemodel 3.2.19
Using erubis 2.7.0
Using journey 1.0.4
Using rack 1.4.5
Using rack-cache 1.2
Using rack-test 0.6.2
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.2.3
Using actionpack 3.2.19
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 3.2.19
Using arel 3.0.3
Using tzinfo 0.3.42
Using activerecord 3.2.19
Using activeresource 3.2.19
Using bundler 1.7.0
Using rack-ssl 1.3.4
Using json 1.8.1
Using rdoc 3.12.2
Using thor 0.19.1
Using railties 3.2.19
Using rails 3.2.19
Using acts-as-taggable-on 2.4.1
Using coderay 1.1.0
Using haml 4.0.5
Using jquery-rails 3.1.2
Using mysql2 0.3.14
Using net-ldap 0.3.1
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using rbpdf 1.18.2
Using redcarpet 2.3.0
Using redmine_acts_as_taggable_on 1.0.0
Using render_parent 0.0.5
Using request_store 1.0.5
Using rmagick 2.13.3
Using vcard 0.2.12
Using ya2yaml 0.31
Your bundle is complete!
```

**Comment by arnisjuraga** [comment]
The same here. After upgrade to Redmine 3.0.1
Please, can You fix it?

**Comment by u2mike** [comment]
same problem in redmine 3.0.3
installation okay but when i want to edit an existing wiki page i get the following debugging errors:

Completed 500 Internal Server Error in 14ms (ActiveRecord: 1.9ms)

ActionView::Template::Error (':parent' is not an ActiveModel-compatible object. It must implement :to_partial_path.):
    1: <%= javascript_include_tag 'image_paste.js', :plugin => 'redmine_image_clipboard_paste' %>
    2: <%= render :parent, {:you_can_pass => :locals} %>
  vendor/bundle/ruby/2.0.0/gems/actionview-4.2.1/lib/action_view/renderer/partial_renderer.rb:478:in `partial_path'
  vendor/bundle/ruby/2.0.0/gems/actionview-4.2.1/lib/action_view/renderer/partial_renderer.rb:382:in`setup'
  vendor/bundle/ruby/2.0.0/gems/actionview-4.2.1/lib/action_view/renderer/partial_renderer.rb:293:in `render'
  vendor/bundle/ruby/2.0.0/gems/actionview-4.2.1/lib/action_view/renderer/renderer.rb:47:in`render_partial'
  vendor/bundle/ruby/2.0.0/gems/actionview-4.2.1/lib/action_view/helpers/rendering_helper.rb:35:in `render'
  plugins/redmine_image_clipboard_paste/app/views/wiki/edit.html.erb:2:in`_plugins_redmine_image_clipboard_paste_app_views_wiki_edit_html_erb___3152079102171262533_70101096101660'
  vendor/bundle/ruby/2.0.0/gems/actionview-4.2.1/lib/action_view/template.rb:145:in `block in render'

**Comment by codyliou** [comment]
same problem in redmine 3.1.0

Completed 500 Internal Server Error in 89ms (ActiveRecord: 14.8ms)

ActionView::Template::Error (':parent' is not an ActiveModel-compatible object. It must implement :to_partial_path.):
    1: <%= javascript_include_tag 'image_paste.js', :plugin => 'redmine_image_clipboard_paste' %>
    2: <%= render :parent, {:you_can_pass => :locals} %>
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by DJUserkent** [comment]
This fork works better
- https://github.com/thorin/redmine_image_clipboard_paste

also see discussion
- https://www.redmine.org/boards/3/topics/40491
