### ISSUE TITLE
Doesn't appear to work on 2.6.0

### ISSUE THREAD

**Issue by tlaskows** [credativUK/redmine_image_clipboard_paste#15]
It displays an icon of a broken image link when pasted into issue edit box.

**Comment by grplyler** [comment]
It works for me on 2.6 but only when i drag the image from finder. If i copy the image from finder, only the finder image icon shows in the post.

**Comment by leozhengcn** [comment]
this plugin can not work properly in my Redmine 2.6.3 windows version. Could anyone give me a hand? Thanks great!
1. The plugin can not show in the  admin->plugins web page.

## 2. when I try to access my redmine "issue" page, an internal error shows:

Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

## If you are the Redmine administrator, check your log files for details about the error.

## 3.check the redmine/log/production.log, there is following infor: 

ActionView::Template::Error (':parent' is not an ActiveModel-compatible object that returns a valid partial path.):
    1: <%= javascript_include_tag 'image_paste.js', :plugin => 'redmine_image_clipboard_paste' %>
    2: <%= render :parent, {:you_can_pass => :locals} %>
    3: 
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/renderer/partial_renderer.rb:385:in `partial_path'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/renderer/partial_renderer.rb:295:in`setup'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/renderer/partial_renderer.rb:221:in `render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/renderer/renderer.rb:41:in`render_partial'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/helpers/rendering_helper.rb:27:in `render'
  plugins/redmine_image_clipboard_paste/app/views/wiki/edit.html.erb:2:in`_plugins_redmine_image_clipboard_paste_app_views_wiki_edit_html_erb___100107568_61242144'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/template.rb:145:in `block in render'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/notifications.rb:125:in`instrument'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/template.rb:143:in `render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/renderer/template_renderer.rb:47:in`block (2 levels) in render_template'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in`block in instrument'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in`instrument'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/renderer/template_renderer.rb:46:in`block in render_template'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/renderer/template_renderer.rb:45:in`render_template'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/renderer/template_renderer.rb:18:in `render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/renderer/renderer.rb:36:in`render_template'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_view/renderer/renderer.rb:17:in `render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:110:in`_render_template'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/streaming.rb:225:in `_render_template'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:103:in`render_to_body'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/compatibility.rb:50:in`render_to_body'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:88:in `render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:16:in`render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/core_ext/benchmark.rb:5:in`block in ms'
  D:/redmine-2.6.3/ruby/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/core_ext/benchmark.rb:5:in`ms'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:83:in`cleanup_view_runtime'
  vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:39:in`render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:5:in`send_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in`process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:513:in`_run__236837106__process_action__212179534__callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in`process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `block in instrument'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in`process'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `block in action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in`call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in`call'
  vendor/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in`each'
  vendor/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in`call'
  vendor/bundle/ruby/2.0.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
  vendor/bundle/ruby/2.0.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in`call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/etag.rb:23:in`call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in`call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in`call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in`call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in`call'
  vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__999746743__call__763149019__callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in`__run_callback'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in`run_callbacks'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
  vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in`block in call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
  vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in`call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in`call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in`call'
  vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
  vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in`fetch'
  vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
  vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in`call!'
  vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/engine.rb:484:in`call'
  vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in`method_missing'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:64:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in`each'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `call'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:82:in`block in pre_process'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:80:in `catch'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:80:in`pre_process'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:55:in `process'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:41:in`receive_data'
  vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:187:in `run_machine'
  vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:187:in`run'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/backends/base.rb:73:in `start'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/server.rb:162:in`start'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/controllers/controller.rb:87:in `start'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/runner.rb:200:in`run_command'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/runner.rb:156:in `run!'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/bin/thin:6:in`<top (required)>'
  bin/thin:16:in `load'
  bin/thin:16:in`<main>'
