### ISSUE TITLE
Error on Redmine 3.1.1 when editing a wiki page

### ISSUE THREAD

**Issue by Mathieu4D** [credativUK/redmine_image_clipboard_paste#25]
Hello,
I installed this plugin and when I try to edit a wiki page, I have this error.
For the moment, I uninstall it, but if you need more informations, there is no problem.
Mathieu

Started GET "/projects/4d/wiki/Redmine_et_Perforce/edit" for 192.168.6.47 at 2015-10-22 15:01:58 +0200
Processing by WikiController#edit as HTML
  Parameters: {"project_id"=>"d", "id"=>"Red_et_Per"}
  Current user: mathieu.steininger@4d.com (id=65)
  Rendered plugins/redmine_image_clipboard_paste/app/views/wiki/edit.html.erb within layouts/base (2.2ms)
Completed 500 Internal Server Error in 12ms (ActiveRecord: 0.8ms)

ActionView::Template::Error (':parent' is not an ActiveModel-compatible object. It must implement :to_partial_path.):
    1: <%= javascript_include_tag 'image_paste.js', :plugin => 'redmine_image_clipboard_paste' %>
    2: <%= render :parent, {:you_can_pass => :locals} %>
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by ccelis5215** [comment]
Hello, same problem here after migrating to 3.1.2

Redmine 3.1.2.stable.14890
Environment:
  Redmine version     3.1.2.stable.14890
  Ruby version           2.2.1-p85 (2015-02-26) [x86_64-linux]
  Rails version            4.2.5
  Environment            production
  Database adapter    Mysql2
SCM:
  Subversion               1.8.8
  Git                            1.9.1
  Filesystem                     

---

Started GET "/proyectos/projects/ms-qa/wiki/Wiki/edit" for 192.168.1.31 at 2015-12-01 07:48:41 -0430
Processing by WikiController#edit as HTML
  Parameters: {"project_id"=>"ms-qa", "id"=>"Wiki"}
  Current user: ccelis (id=12)
  Rendered plugins/redmine_image_clipboard_paste/app/views/wiki/edit.html.erb within layouts/base (3.1ms)
Completed 500 Internal Server Error in 23ms (ActiveRecord: 1.2ms)

ActionView::Template::Error (':parent' is not an ActiveModel-compatible object. It must implement :to_partial_path.):
    1: <%= javascript_include_tag 'image_paste.js', :plugin => 'redmine_image_clipboard_paste' %>
    2: <%= render :parent, {:you_can_pass => :locals} %>
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by gregal** [comment]
Same problem.

**Comment by archonwang** [comment]
+1

**Comment by DJUserkent** [comment]
Try Thorin's fork:  https://github.com/thorin/redmine_image_clipboard_paste
